### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by YoogottamK**
- [x] Changed headings to give some space to the content below
- [x] Changed the about megathon to look better
- [x] Shifted "Click here to know more" after the table. Logically, they will know something then more about it.
- [x] Removed the responsive-table class from table, it wasn't looking good on mobile / small devices
- [x] Made _APPLY NOW_ text more visible
- [x] Migrated events data from yaml to json. Now we have new lines!!
- [x] Made the events section look better
- [x] Centered the medal image in prizes section

Screens (now | earlier)
---
megathon_about_after
megathon_about_before
megathon_format_after
megathon_format_before
megathon_schedule_after
megathon_schedule_before
megathon_apply_after
megathon_apply_before
megathon_events_after
megathon_events_before
megathon_prizes_after
megathon_prizes_before

### CODE REVIEW

**Comment by GaurangTandon** [comment]
@YoogottamK No! One must never use inline styles... It causes maintenance problems later... Just use a separate class and add relevant styles in the css file

**Comment by YoogottamK** [comment]
@GaurangTandon Removed inline styling and added a `.heading` in custom-materialize.css

**Comment by YoogottamK** [comment]
Few more changes made:

- Made APPLY NOW text more visible
- Migrated events data from yaml to json. Now we have new lines!!
- Made the events section look better
- Centered the medal image in prizes section

**Comment by zubairabid** [comment]
Rebase to current origin master. It's 2 commits behind.

**Comment by zubairabid** [comment]
@zubairabid @yoogottamk for #2 just v-align the videos, that should be good enough and a universal-ish solution

**Pull request merged**
